Necropolis/Controllers/InformationEditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Necropolis.Helpers;
using Necropolis.Models;

namespace Necropolis.Controllers
{
    public class InformationEditorController : Controller
    {
        // GET: InformationEditor
        public ActionResult Index()
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            var model = InformationManager.GetInformationCatalog();
            return View(model);
        }

        // GET: InformationEditor/Details/5
        public ActionResult Details(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth", Request.RequestContext.RouteData.Values);
            try
            {
                InformationManager.DeleteItem(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: InformationEditor/Create
        public ActionResult Create()
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");

            var model = new InformationItemModel();
            model.Id = InformationManager.GenerateId();
            return View(model);
        }

        // POST: InformationEditor/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(InformationItemModel model)
        {
            try
            {
                if (!AuthController.CheckAuth(Request.Cookies))
                    return RedirectToAction("Auth", "Auth");
                model.Date = DateTime.Now;
                InformationManager.SaveItem(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: InformationEditor/Edit/5
        public ActionResult PreView(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            var item = InformationManager.GetItem(id);
            if (item != null)
                return View(item);
            return RedirectToAction("Index");
        }

        public ActionResult ChangeMenuStatus(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            InformationManager.ChangeMenuStatus(id);
            return RedirectToAction("Index");
        }
        
                public ActionResult ChangePublishStatus(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            InformationManager.ChangePublishStatus(id);
            return RedirectToAction("Index");
        }

        // GET: InformationEditor/Edit/5
        public ActionResult Edit(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            var item = InformationManager.GetItem(id);
            if (item != null)
                return View(item);
            return RedirectToAction("Index");
        }

        // POST: InformationEditor/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(InformationItemModel model)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            try
            {
                model.Date = DateTime.Now;
                InformationManager.SaveItem(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: InformationEditor/Delete/5
        public ActionResult Delete(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            try
            {
               InformationManager.DeleteItem(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

Necropolis/Views/InformationEditor/Create.cshtml
@using Necropolis.Models
@model Necropolis.Models.InformationItemModel
@{
    ViewBag.Title = "Редактор";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.MenuTab = "control";
    var itemTypes = Enum.GetValues(typeof(InformationItemType)).OfType<InformationItemType>().ToList();

}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="wrap">
                    <h2 class="lines">Добавить статью</h2>
                </div>
                <div class="span3">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        <div class="form-group">
                            <h3>Вид статьи</h3>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Type, new SelectList(itemTypes), new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <h3>Заголовок</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @id = "priceEditor" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <h3>Путевое имя</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.RouteName, new { htmlAttributes = new { @class = "form-control", @id = "priceEditor" } })
                                @Html.ValidationMessageFor(model => model.RouteName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group" style="margin: 23px 0; padding: 0;">
                            <div class="">
                                <input type="submit" value="Создать" class="btn btn-default" />

                                <input type="button" class="btn btn-default" value="Отмена" style="margin-left: 69px;" onclick="location.href = '@Url.Action( "Index", "InformationEditor" )'" />

                            </div>

                        </div>
                    </div>
                </div>
                <div class="span8">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <h3>Текст статьи</h3>
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control hide" } })
                                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/site/informationEditor.js"></script>
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
}

Necropolis/Views/InformationEditor/Edit.cshtml
@using Necropolis.Models
@model Necropolis.Models.InformationItemModel
@{
    ViewBag.Title = "Редактор";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.MenuTab = "control";
    var itemTypes = Enum.GetValues(typeof(InformationItemType)).OfType<InformationItemType>().ToList();
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="wrap">
                    <h2 class="lines">Редактировать статью</h2>
                </div>
                <div class="span3">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.Published)
                        @Html.HiddenFor(model => model.AddedToMenu)
                        <div class="form-group">
                            <h3>Вид статьи</h3>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Type, new SelectList(itemTypes), new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.Type, "", new {@class = "text-danger"})
                            </div>
                        </div>
                        <div class="form-group">
                            <h3>Заголовок</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control", @id = "priceEditor"}})
                                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                            </div>
                        </div>
                        <div class="form-group">
                            <h3>Путевое имя</h3>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.RouteName, new {htmlAttributes = new {@class = "form-control", @id = "priceEditor"}})
                                @Html.ValidationMessageFor(model => model.RouteName, "", new {@class = "text-danger"})
                            </div>
                        </div>
                        <div class="form-group" style="margin: 23px 0; padding: 0;">
                            <div class="">
                                <input type="submit" value="Сохранить" class="btn btn-default"/>

                                <input type="button" class="btn btn-default" value="Отмена" style="margin-left: 54px;" onclick="location.href = '@Url.Action("Index", "InformationEditor")'"/>

                            </div>

                        </div>
                    </div>
                </div>
                <div class="span8">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <h3>Текст статьи</h3>
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Text, new {htmlAttributes = new {@class = "form-control hide"}})
                                @Html.ValidationMessageFor(model => model.Text, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/site/informationEditor.js"></script>
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
}

Necropolis/Views/InformationEditor/Index.cshtml
@using System.Web.UI.WebControls
@using Necropolis.Models
@model IEnumerable<Necropolis.Models.InformationItemModel>

@{
    ViewBag.Title = "Редактор статей";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.MenuTab = "control";

    var type = "";
    var catalog = Model;
    var forType = Request.QueryString["type"] != null;

    if (forType)
    {
        type = Request["type"];
        catalog = Model.Where(i => i.Type.ToString().ToLower() == type.ToLower());
    }
}





<div class="container">
    <div class="row">
        <div class="span4">
            <div class="wrap one-line-heading">
                <h2 class="line sub-categories-handler">
                    Показать @if (forType)
                    {
                    @String.Concat("- ", type.Replace("_", " "));
                    }
                    else
                    { @String.Concat("- ", "все");
                    }
                </h2>
            </div>
            <ul class="list list-padding sub-categories">
                <li><a href="@Url.Action("index", "InformationEditor")">Все</a></li>
                <li><a href="@Url.Action("index", "InformationEditor", new {@type = "информационная_статья"})">Информационные статьи</a></li>
                <li><a href="@Url.Action("index", "InformationEditor", new {@type = "Вопрос"})">Вопросы</a></li>
            </ul>
        </div>

        <div class="span8">
            <div class="wrap one-line-heading">
                <h2 class="line">Редактор статей</h2>
            </div>
        </div>
        <div class="span12">

            <table class="table">
                <tr>
                    <th class="span1" style="text-align: center;">
                        Статус
                    </th>
                    <th class="span1" style="text-align: center;">
                        В меню
                    </th>
                    <th class="span1" style="text-align: center;">
                        Тип
                    </th>
                    <th class="span3">
                        Заголовок
                    </th>
                    <th class="span3">
                        Путевое имя
                    </th>
                    <th class="span3">
                        Дата изменения
                    </th>
                    <th>
                        @Html.ActionLink("Добавить", "Create")
                    </th>
                </tr>

                @foreach (var item in catalog)
                {
                <tr>
                    <td style="text-align: center; font-size: 20px;">
                        <a href="@Url.Action("ChangePublishStatus", new {id = item.Id})">
                            @if (item.Published)
                            {
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            }
                            else
                            {
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>

                            }
                        </a>
                    </td>
                    <td style="text-align: center; font-size: 20px;">
                        <a href="@Url.Action("ChangeMenuStatus", new {id = item.Id})">
                            @if (item.AddedToMenu)
                            {
                            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                            }
                            else
                            {
                            <span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span>

                            }
                        </a>
                    </td>
                    <td style="text-align: center; font-size: 20px;">
                        @*@Html.DisplayFor(modelItem => item.Type)*@
                        @if (item.Type == InformationItemType.Вопрос)
                        {
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                        }
                        else if (item.Type == InformationItemType.Информационная_статья)
                        {
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        }
                        else
                        {
                        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>

                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        /@Html.DisplayFor(modelItem => item.RouteName)
                    </td>
                    <td>
                        @item.Date.ToString("f")
                    </td>
                    <td>
                        @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |

                        @Html.ActionLink("Превью", "PreView", new { id = item.Id }) |

                        @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
                    </td>
                </tr>
                }

            </table>

        </div>
    </div>
</div>

Necropolis/Views/InformationEditor/PreView.cshtml
@using Necropolis.Models
@model Necropolis.Models.InformationItemModel
@{
    ViewBag.Title = "Редактор";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.MenuTab = "control";
    var informationArticle = Model;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">

            <div class="span12">
                <div class="wrap">

                    <h2>Превью</h2>
                    <br />
                    @Html.ActionLink("Назад", "Index", "InformationEditor") |
                    @Html.ActionLink("Редактировать", "Edit", new { id = informationArticle.Id }) |
                    <a href="@Url.Action("ChangePublishStatus", new {id = informationArticle.Id})">
                        @if (informationArticle.Published)
                        {
                        <text>Снять с публикаци</text>
                        }
                        else
                        {
                        <text>Опубликовать</text>
                        }
                    </a>


                </div>
            </div>
        </div>
        <div class="row">

            <div class="span12"
                 @if (informationArticle.Type == InformationItemType.Вопрос) { <text> itemscope itemtype="http://schema.org/Question" </text>    }>
                <div class="wrap" id="@informationArticle.RouteName">
                    <h2 class="lines"
                        @if (informationArticle.Type == InformationItemType.Вопрос) { <text> itemprop="name" </text>    }>

                        @informationArticle.Title
                    </h2>
                </div>
                <div class="center-text left"
                     @if (informationArticle.Type == InformationItemType.Вопрос) { <text> itemprop="acceptedAnswer" itemscope itemtype="http://schema.org/Answer" </text>    }>
                    @(new HtmlString(informationArticle.Text.Replace("<ul>", "<ul class='list list - padding'>")))
                </div>

                <div class="vensel-big">
                    <img src="../../Content/images/necropolis-vensel.png" />
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}