Necropolis/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Necropolis.Models;

namespace Necropolis.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public static bool CheckAuth(HttpCookieCollection cookies)
        {
            return cookies.Get("Necropolis") != null;
        }

        [HttpGet]
        public ActionResult Auth()
        {
            if (CheckAuth(Request.Cookies))
                return RedirectToRoute("Control");
            var model = new AuthModel();
            return View(model);
        }

        [HttpGet]
        public ActionResult LogOut()
        {
            Response.Cookies.Remove("Necropolis");

            if (Request.Cookies["Necropolis"] != null)
            {
                var c = new HttpCookie("Necropolis");
                c.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(c);
            }
            return RedirectToRoute("Home");
        }

        [HttpPost]
        public ActionResult Auth(AuthModel model)
        {
            if (model.Login == "necropol" && model.Password == DateTime.Now.Day.ToString() + "pas")
            {
                HttpCookie myCookie = new HttpCookie("Necropolis");
                myCookie.Expires = DateTime.Now.AddDays(1d);
                Response.Cookies.Add(myCookie);
                return RedirectToRoute("Control");
            }
            ViewBag.Wrong = true;
            return View();
        }
    }
}

Necropolis/Controllers/CatalogController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Necropolis.Helpers;
using Necropolis.Models;
using Newtonsoft.Json;
using static System.IO.File;

namespace Necropolis.Controllers
{
	public class CatalogController : Controller
	{
		// GET: Catalog
		public ActionResult Index()
		{
			var model = CatalogManager.GetCatalog();
			return View(model);
		}
	}
}

Necropolis/Controllers/CatalogEditorController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Necropolis.Helpers;
using Necropolis.Models;
using Newtonsoft.Json;
using static System.IO.File;

namespace Necropolis.Controllers
{
    public class CatalogEditorController : Controller
    {
        // GET: Catalog
        public ActionResult Index()
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");

            var model = CatalogManager.GetCatalog();
            return View(model);
        }

        // GET: Catalog/Details/5
        public ActionResult Details(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth", Request.RequestContext.RouteData.Values);
            try
            {
                CatalogManager.DeleteItem(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: Catalog/Create
        public ActionResult Create()
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth", Request.RequestContext.RouteData.Values);
            var model = new CatalogItemModel();
            model.Id = CatalogManager.generateID();
            model.Image = "/Content/images/catalog/icons/no-image.png";
            model.ImagePreview = "/Content/images/catalog/icons/no-image.png";
            return View(model);
        }

        // POST: Catalog/Create
        [HttpPost]
        public ActionResult Create(CatalogItemModel model)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            try
            {
                CatalogManager.SaveItem(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Catalog/Edit/5
        public ActionResult Edit(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            var item = CatalogManager.GetItem(id);
            if (item != null)
                return View(item);
            return RedirectToAction("Index");
        }

        // POST: Catalog/Edit/5
        [HttpPost]
        public ActionResult Edit(CatalogItemModel model)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth");
            try
            {
                CatalogManager.SaveItem(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Catalog/Delete/5
        public ActionResult Delete(string id)
        {
            if (!AuthController.CheckAuth(Request.Cookies))
                return RedirectToAction("Auth", "Auth" );
            try
            {
                CatalogManager.DeleteItem(id);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }



        [HttpPost]
        public async Task<JsonResult> UploadFile(string id)
        {

            try
            {
                foreach (string file in Request.Files)
                {
                    var fileContent = Request.Files[file];
                    if (fileContent != null && fileContent.ContentLength > 0)
                    {
                        // get a stream
                        var stream = fileContent.InputStream;
                        // and optionally write the file to disk
                        var fileName = "IMG" + id + Path.GetExtension(fileContent.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/images/catalog"), fileName);

                        using (var image = System.Drawing.Image.FromStream(stream))
                        {
                            using (var newImage = CatalogManager.ScaleImageTo(image, 400, 300))
                            {
                                CatalogManager.AddWatermark(image);
                                image.Save(path);

                                CatalogManager.AddWatermark(newImage);
                                newImage.Save(path + ".[small]" + Path.GetExtension(fileContent.FileName));
                            }
                        }
                    }
                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Upload failed");
            }

            return Json("File uploaded successfully");
        }

        //public bool CheckAuth()
        //{
        //    return Request.Cookies.Get("Necropolis") != null;
        //}
        //[HttpGet]
        //public ActionResult Auth()
        //{
        //    var model = new AuthModel();
        //    return View(model);
        //}
        //[HttpPost]
        //public ActionResult Auth(AuthModel model)
        //{
        //    if (CheckAuth())
        //        return RedirectToAction("Index");
        //    if (model.Login == "necropol" && model.Password == DateTime.Now.Day.ToString() + "pas")
        //    {
        //        HttpCookie myCookie = new HttpCookie("Necropolis");
        //        myCookie.Expires = DateTime.Now.AddDays(1d);
        //        Response.Cookies.Add(myCookie);
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.Wrong = true;
        //    return View();
        //}
    }
}

Necropolis/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Necropolis.Controllers
{
    public class ServicesController : Controller
    {
        // GET: RitualServices

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FuneralSets()
        {
            return View();
        }

        public ActionResult RitualHalls()
        {
            return View();
        }
        public ActionResult RitualServices()
        {
            return View();
        }

    }
}

Necropolis/Views/Shared/_Layout.cshtml
@using Necropolis.Helpers
@{
    var description = ViewBag.Description != null ? ViewBag.Description : "Похоронные и ритуальные услуги в ярославле";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta charset="utf-8">
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <meta name="description" content="@description">
    <meta name="author" content="MnemoN">
    @RenderSection("css", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-97098014-1', 'auto');
        ga('send', 'pageview');

    </script>
    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="~/Scripts/jquery.mobile.customized.min.js"></script>
    <!--<![endif]-->
    <!--[if lt IE 8]>
        <div style='text-align:center'><a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/img/upgrade.jpg" border="0"alt=""/></a></div>
    <![endif]-->
    <!--[if lt IE 9]>
      <link rel="stylesheet" href="~/Content/ie.css" type="text/css" media="screen">
      <script src="~/Scripts/html5shiv.js"></script>
    <![endif]-->
    <title>Похоронные и ритуальные услуги в Ярославле - Некрополь - @ViewBag.Title</title>
</head>
<body>
    <header class="colomns-top">
        <div class="container">
            <div class="row">

                <div class="span12">
                    <div class="brand" id="brand">
                        <a href="@Url.Action("Index", "Home")"><img class="logo" src="../../Content/images/logo.png" /></a>
                    </div>
                    <div class="navbar_" id="menu-frame">
                        <div class="navbar-inner">
                            <ul class="nav sf-menu " id="menu" active-tab="@ViewBag.MenuTab">
                                <li id="home">@Html.ActionLink("Главная", "Index", "Home")</li>
                                <li id="services">
                                    <a href="#">Услуги</a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="@Url.Action("RitualServices", "Services")">Ритуальные услуги</a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="@Url.Action("RitualServices", "Services", new {set = "muslim"})">Мусульманские похороны</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("RitualServices", "Services", new {set = "embalming" })">Бальзамирование</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("RitualServices", "Services", new {set = "cremation"})">Кремация</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("RitualServices", "Services", new {set = "transport"})">Транспортировка</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("RitualServices", "Services", new {set = "care"})">Уход за захоранениями</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("RitualServices", "Services", new {set = "contract"})">Прижизненный договор</a>
                                                </li>
                                            </ul>

                                        </li>
                                        <li><a href="@Url.Action("RitualHalls", "Services")">Ритуальные залы</a></li>
                                        <li>
                                            <a href="@Url.Action("FuneralSets", "Services")">Комплексы похоронных услуг</a>
                                            <ul class="sub-menu">
                                                <li>
                                                    <a href="@Url.Action("FuneralSets", "Services", new {set = "basic"})">Базовый</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("FuneralSets", "Services", new {set = "extended"})">Расширенный</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("FuneralSets", "Services", new {set = "premium"})">Премиум</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li id="catalog">
                                    <a href="@Url.Action("Index", "Catalog")">
                                        Каталог
                                    </a>
                                    <ul class="sub-menu">
                                        <li><a href="@Url.Action("index", "Catalog", new {@type="кресты"})">Кресты</a></li>
                                        <li><a href="@Url.Action("index", "Catalog", new {@type="памятники"})">Памятники</a></li>
                                        <li><a href="@Url.Action("index", "Catalog", new {@type="траурные_ленты"})">Траурные ленты</a></li>
                                        <li><a href="@Url.Action("index", "Catalog", new {@type="венки"})">Венки</a></li>
                                        <li><a href="@Url.Action("index", "Catalog", new {@type="гробы"})">Гробы</a></li>
                                        <li><a href="@Url.Action("index", "Catalog", new {@type="другие_товары"})">Другие товары</a></li>
                                    </ul>
                                </li>
                                <li id="information">
                                    <a href="@Url.Action("Information", "Information")">
                                        Информация
                                    </a>
                                    @{
                                        var informationArticles = InformationManager.GetMenuMembers();
                                        if (informationArticles != null && informationArticles.Count > 0)
                                        {
                                        <ul class="sub-menu">
                                            @foreach (var informationItemModel in informationArticles)
                                            {
                                            <li>
                                                <a href="@Url.Action("Information", "Information",
                                                                     new {set = informationItemModel.RouteName})">
                                                    @informationItemModel.Title
                                                </a>

                                            </li>
                                            }
                                        </ul>

                                        }
                                    }

                                </li>
                                <li id="contacts">@Html.ActionLink("Контакты", "Contact", "Home")</li>
                                @if (Request.Cookies.Get("Necropolis") != null)
                                {
                                <li id="control">
                                    <a href="@Url.Action("Index", "Control")">
                                        Управление
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a href="@Url.Action("Index", "CatalogEditor")">
                                                Редактор каталога
                                            </a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "InformationEditor")">
                                                Редактор статей
                                            </a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("LogOut", "Auth")">
                                                Выход
                                            </a>
                                        </li>
                                    </ul>

                                </li>
                                }
                            </ul>
                        </div>
                    </div>

                </div>
                <div class="span12 ">
                    <section class="social-block call" itemscope itemtype="http://schema.org/Organization">
                        <meta itemprop="name" content="Похоронный дом Некрополь">
                        <meta itemprop="address" content="г. Ярославль ул. Загородный сад, д. 11 (территория б-цы им. Соловьёва) Въезд с ул. Харитонова">
                        <img src="~/Content/images/phone-icon.png" alt="">
                        <div class="phone">
                            <span class="social-title"><strong>Позвоните нам </strong></span><br />
                            <a class="social-title" href="tel:+4852733998">
                                <span><span itemprop="telephone">(4852) 733-998</span> (круглосуточно)</span>
                            </a>
                            <br />
                            <a class="social-title" href="tel:+4852942948">
                                <span itemprop="telephone">(4852) 942-948</span>
                            </a>
                            <br />
                            <span>Часы работы: круглосуточно</span>

                        </div>

                    </section>
                </div>
            </div>
        </div>
    </header>
    <div class="body-content colomns-middle">
        <div class="container">
            @RenderBody()
            <div id="goUp" class="go-up">
                <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
            </div>
        </div>
    </div>
    <footer class="colomns-bottom">
        <div class="container">
            <div class="row">

                <div class="span12 ">
                    <section class="social-block">
                        <img src="~/Content/images/phone-icon.png" alt="">
                        <div class="phone">
                            <span class="social-title"><strong>Позвоните нам </strong></span><br />
                            <a class="social-title" href="tel:+4852733998">
                                <span>(4852) 733-998 (круглосуточно)</span>
                            </a>
                            <br />
                            <a class="social-title" href="tel:+4852942948">
                                <span>(4852) 942-948</span>
                            </a>
                            <br />
                            <span>Часы работы: круглосуточно</span>

                        </div>

                    </section>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    NECROPOLIS &copy; @DateTime.Now.Year &nbsp; | Некрополь - Похоронный дом  | Полный комплекс ритуальных услуг в Ярославле
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>